# Generated by Django 2.2.2 on 2019-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190613_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_activity',
            name='action_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='account_activity',
            name='activity_type',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_login_information',
            name='log_out_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user_login_information',
            name='login_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
