# Generated by Django 2.2.2 on 2019-06-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_type', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('item_name', models.CharField(max_length=30)),
                ('company', models.CharField(max_length=30)),
                ('size', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
            ],
        ),
    ]
