# Generated by Django 2.2.2 on 2019-06-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_bought',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_cost',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
